Checkpoint successfully loaded from checkpoints/BalanceLoss/enet_checkpoint_epoch_96.pth (Epoch 96)
Traceback (most recent call last):
  File "eval.py", line 96, in <module>
    evaluate()
  File "eval.py", line 77, in evaluate
    print(f"length: {instance_losses.shape}")
AttributeError: 'list' object has no attribute 'shape'
